# Generated by Django 5.2.15 on 2026-06-21 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(blank=True, choices=[('cidade', 'Cidade'), ('vila', 'Vila'), ('regiao', 'Região'), ('base', 'Base'), ('outro', 'Outro')], max_length=10, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Notas')),
                ('status', models.CharField(blank=True, max_length=150, verbose_name='Status Atual')),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locais',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Objetivos')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('concluida', 'Concluída')], default='ativa', max_length=10, verbose_name='Status')),
                ('resultado', models.TextField(blank=True, verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Missão',
                'verbose_name_plural': 'Missões',
                'ordering': ['status', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Personagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('raca', models.CharField(blank=True, max_length=80, verbose_name='Raça')),
                ('classe', models.CharField(blank=True, max_length=120, verbose_name='Classe')),
                ('nivel', models.PositiveSmallIntegerField(default=1, verbose_name='Nível')),
                ('forca', models.PositiveSmallIntegerField(default=10, verbose_name='Força')),
                ('destreza', models.PositiveSmallIntegerField(default=10, verbose_name='Destreza')),
                ('constituicao', models.PositiveSmallIntegerField(default=10, verbose_name='Constituição')),
                ('inteligencia', models.PositiveSmallIntegerField(default=10, verbose_name='Inteligência')),
                ('sabedoria', models.PositiveSmallIntegerField(default=10, verbose_name='Sabedoria')),
                ('carisma', models.PositiveSmallIntegerField(default=10, verbose_name='Carisma')),
                ('bonus_proficiencia', models.PositiveSmallIntegerField(default=2, verbose_name='Bônus de Proficiência')),
                ('ca', models.PositiveSmallIntegerField(default=10, verbose_name='Classe de Armadura')),
                ('pv_maximo', models.PositiveSmallIntegerField(default=1, verbose_name='PV Máximo')),
                ('pv_atual', models.IntegerField(default=1, verbose_name='PV Atual')),
                ('pv_temporario', models.PositiveSmallIntegerField(default=0, verbose_name='PV Temporário')),
                ('deslocamento', models.PositiveSmallIntegerField(default=9, verbose_name='Deslocamento (m)')),
                ('background', models.TextField(blank=True, verbose_name='Background / História')),
                ('moedas_pc', models.PositiveIntegerField(default=0, verbose_name='Peças de Cobre')),
                ('moedas_pp', models.PositiveIntegerField(default=0, verbose_name='Peças de Prata')),
                ('moedas_pe', models.PositiveIntegerField(default=0, verbose_name='Peças de Electro')),
                ('moedas_po', models.PositiveIntegerField(default=0, verbose_name='Peças de Ouro')),
                ('moedas_pl', models.PositiveIntegerField(default=0, verbose_name='Peças de Platina')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Personagem',
                'verbose_name_plural': 'Personagens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ResumoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número da Sessão')),
                ('titulo', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo')),
            ],
            options={
                'verbose_name': 'Resumo de Sessão',
                'verbose_name_plural': 'Resumos de Sessão',
                'ordering': ['-numero'],
            },
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Papel')),
                ('relacao_grupo', models.CharField(choices=[('aliado', 'Aliado'), ('suspeito', 'Suspeito'), ('inimigo', 'Inimigo'), ('neutro', 'Neutro'), ('desconhecido', 'Desconhecido')], default='neutro', max_length=15, verbose_name='Relação com o Grupo')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npcs', to='campanha.local')),
            ],
            options={
                'verbose_name': 'NPC',
                'verbose_name_plural': 'NPCs',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='InformacaoImportante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Informação')),
                ('missao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='campanha.missao')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infos', to='campanha.npc')),
            ],
            options={
                'verbose_name': 'Informação Importante',
                'verbose_name_plural': 'Informações Importantes',
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('equipado', 'Equipado'), ('mochila', 'Mochila'), ('magico', 'Item Mágico')], default='mochila', max_length=10, verbose_name='Tipo')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('atributos_efeito', models.TextField(blank=True, verbose_name='Atributos / Efeito')),
                ('lore', models.TextField(blank=True, verbose_name='Lore / História')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='RecursoDeCombate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Efeito')),
                ('usos_totais', models.PositiveSmallIntegerField(default=1, verbose_name='Usos Totais')),
                ('usos_restantes', models.PositiveSmallIntegerField(default=1, verbose_name='Usos Restantes')),
                ('recuperacao', models.CharField(choices=[('curto', 'Descanso Curto'), ('longo', 'Descanso Longo'), ('nenhum', 'Nenhum')], default='longo', max_length=10, verbose_name='Recuperação')),
                ('checklist_turno', models.TextField(blank=True, verbose_name='Checklist de Turno')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Recurso de Combate',
                'verbose_name_plural': 'Recursos de Combate',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pericia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(choices=[('acrobacia', 'Acrobacia'), ('adestrar_animais', 'Adestrar Animais'), ('arcanismo', 'Arcanismo'), ('atletismo', 'Atletismo'), ('atuacao', 'Atuação'), ('enganacao', 'Enganação'), ('furtividade', 'Furtividade'), ('historia', 'História'), ('intimidacao', 'Intimidação'), ('intuicao', 'Intuição'), ('investigacao', 'Investigação'), ('medicina', 'Medicina'), ('natureza', 'Natureza'), ('percepcao', 'Percepção'), ('persuasao', 'Persuasão'), ('prestidigitacao', 'Prestidigitação'), ('religiao', 'Religião'), ('sobrevivencia', 'Sobrevivência')], max_length=40)),
                ('proficiente', models.BooleanField(default=False, verbose_name='Proficiente')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pericias', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Perícia',
                'verbose_name_plural': 'Perícias',
                'constraints': [models.UniqueConstraint(fields=('personagem', 'identificador'), name='uniq_pericia_personagem')],
            },
        ),
        migrations.CreateModel(
            name='Salvaguarda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(choices=[('forca', 'Força'), ('destreza', 'Destreza'), ('constituicao', 'Constituição'), ('inteligencia', 'Inteligência'), ('sabedoria', 'Sabedoria'), ('carisma', 'Carisma')], max_length=20)),
                ('proficiente', models.BooleanField(default=False, verbose_name='Proficiente')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvaguardas', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Salvaguarda',
                'verbose_name_plural': 'Salvaguardas',
                'constraints': [models.UniqueConstraint(fields=('personagem', 'identificador'), name='uniq_salvaguarda_personagem')],
            },
        ),
    ]
