# Generated by Django 5.2.6 on 2026-06-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='iniciativa_bonus',
            field=models.SmallIntegerField(default=0, help_text='Adicione aqui qualquer bônus extra (ex.: Bônus de Proficiência se tiver o feat/recurso correspondente).', verbose_name='Bônus extra de Iniciativa'),
        ),
    ]
