# Generated by Django 5.2.6 on 2026-06-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0002_iniciativa_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='npcs/', verbose_name='Imagem'),
        ),
    ]
