# Generated by Django 5.2.6 on 2026-06-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0003_npc_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missao',
            options={'ordering': ['tipo', 'titulo'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AddField(
            model_name='missao',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Missão Principal'), ('contrato', 'Contrato'), ('secundaria', 'Missão Secundária')], default='secundaria', max_length=12, verbose_name='Tipo'),
        ),
    ]
