# Generated by Django 5.2.6 on 2026-06-21 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0004_missao_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCombate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(blank=True, help_text='Descreva a mecânica, dano, condições, etc. Formatação livre.', verbose_name='Conteúdo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, help_text='Número menor aparece primeiro.', verbose_name='Ordem')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_combate', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Nota de Combate',
                'verbose_name_plural': 'Notas de Combate',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
