# Generated by Django 5.2.15 on 2026-07-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0006_item_magico_sintonizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='locais/', verbose_name='Ilustração'),
        ),
        migrations.AddField(
            model_name='local',
            name='mapa',
            field=models.ImageField(blank=True, help_text='Mapa do local, se houver.', null=True, upload_to='locais/mapas/', verbose_name='Mapa'),
        ),
    ]
