# Generated by Django 5.2.15 on 2026-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0007_local_imagem_local_mapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missao',
            options={'ordering': ['tipo', 'ordem', 'titulo'], 'verbose_name': 'Missão', 'verbose_name_plural': 'Missões'},
        ),
        migrations.AddField(
            model_name='missao',
            name='ordem',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posição no kanban; menor aparece primeiro. Ajustado ao arrastar.', verbose_name='Ordem'),
        ),
    ]
