# Generated by Django 5.2.15 on 2026-07-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0008_alter_missao_options_missao_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='furia_ativa',
            field=models.BooleanField(default=False, verbose_name='Fúria ativa'),
        ),
    ]
