# Generated by Django 5.2.15 on 2026-07-27 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0009_personagem_furia_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='personagem',
            name='bonus_dano_furia',
            field=models.PositiveSmallIntegerField(default=2, help_text='Somado ao dano dos ataques enquanto a Fúria estiver ativa. Cresce com o nível de bárbaro.', verbose_name='Bônus de dano da Fúria'),
        ),
        migrations.CreateModel(
            name='Ataque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('quantidade_dados', models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de Dados')),
                ('faces_dado', models.PositiveSmallIntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20')], default=8, verbose_name='Dado')),
                ('bonus_atributo', models.SmallIntegerField(default=0, help_text='Bônus fixo somado ao dano (ex.: +5 de Força).', verbose_name='Bônus de Atributo')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ataques', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Ataque',
                'verbose_name_plural': 'Ataques',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
