# Generated by Django 5.2.15 on 2026-08-26 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0013_ca_estilo_slot_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('muito_raro', 'Muito Raro'), ('lendario', 'Lendário')], default='comum', max_length=12, verbose_name='Raridade')),
                ('peso', models.DecimalField(decimal_places=2, default=0, help_text='Usado para o total de carga (capacidade = Força × 7,5 kg).', max_digits=6, verbose_name='Peso (kg, por unidade)')),
                ('lore', models.TextField(blank=True, verbose_name='Lore / História')),
                ('cura_qtd_dados', models.PositiveSmallIntegerField(default=1, verbose_name='Qtd. de Dados de Cura')),
                ('cura_faces', models.PositiveSmallIntegerField(choices=[(4, 'd4'), (6, 'd6'), (8, 'd8'), (10, 'd10'), (12, 'd12'), (20, 'd20')], default=4, verbose_name='Dado de Cura')),
                ('cura_bonus', models.SmallIntegerField(default=0, verbose_name='Bônus de Cura')),
                ('efeito_categoria', models.CharField(blank=True, choices=[('nenhum', 'Nenhum'), ('pv_temporario', 'PV Temporário'), ('remove_condicao', 'Remove uma Condição'), ('resistencia_buff', 'Resistência Temporária a um Tipo de Dano'), ('vantagem_buff', 'Vantagem Temporária em um Teste'), ('atributo_buff', 'Bônus Temporário a um Atributo'), ('outro', 'Outro (ver descrição)')], help_text="Só 'PV Temporário' é aplicado automaticamente hoje; as demais categorias aparecem como aviso para aplicar na mão.", max_length=20, verbose_name='Categoria do Efeito Adicional')),
                ('efeito_alvo', models.CharField(blank=True, help_text='Livre — o que significa depende da categoria (ex.: tipo de dano, condição, atributo).', max_length=60, verbose_name='Alvo do Efeito Adicional')),
                ('efeito_valor', models.SmallIntegerField(default=0, verbose_name='Valor do Efeito Adicional')),
                ('efeito_descricao', models.CharField(blank=True, max_length=250, verbose_name='Descrição do Efeito Adicional')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocoes', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Poção',
                'verbose_name_plural': 'Poções',
                'ordering': ['nome'],
            },
        ),
    ]
