# Generated by Django 5.2.15 on 2026-08-26 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campanha', '0015_dados_pocao'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAlquimica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('muito_raro', 'Muito Raro'), ('lendario', 'Lendário')], default='comum', max_length=12, verbose_name='Raridade')),
                ('peso', models.DecimalField(decimal_places=2, default=0, help_text='Usado para o total de carga (capacidade = Força × 7,5 kg).', max_digits=6, verbose_name='Peso (kg, por unidade)')),
                ('lore', models.TextField(blank=True, verbose_name='Lore / História')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases_alquimicas', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Base Alquímica',
                'verbose_name_plural': 'Bases Alquímicas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteAlquimico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('muito_raro', 'Muito Raro'), ('lendario', 'Lendário')], default='comum', max_length=12, verbose_name='Raridade')),
                ('peso', models.DecimalField(decimal_places=2, default=0, help_text='Usado para o total de carga (capacidade = Força × 7,5 kg).', max_digits=6, verbose_name='Peso (kg, por unidade)')),
                ('lore', models.TextField(blank=True, verbose_name='Lore / História')),
                ('reagente', models.CharField(choices=[('vento', 'Vento'), ('luz', 'Luz'), ('trevas', 'Trevas'), ('terra', 'Terra'), ('fogo', 'Fogo'), ('agua', 'Água'), ('natureza', 'Natureza'), ('arcano', 'Arcano')], max_length=12, verbose_name='Reagente')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_alquimicos', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Componente Alquímico',
                'verbose_name_plural': 'Componentes Alquímicos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteCriatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('raridade', models.CharField(choices=[('comum', 'Comum'), ('incomum', 'Incomum'), ('raro', 'Raro'), ('muito_raro', 'Muito Raro'), ('lendario', 'Lendário')], default='comum', max_length=12, verbose_name='Raridade')),
                ('peso', models.DecimalField(decimal_places=2, default=0, help_text='Usado para o total de carga (capacidade = Força × 7,5 kg).', max_digits=6, verbose_name='Peso (kg, por unidade)')),
                ('lore', models.TextField(blank=True, verbose_name='Lore / História')),
                ('tipo_origem', models.CharField(choices=[('beast', 'Beast'), ('monstrosity', 'Monstrosity'), ('giant', 'Giant'), ('construct', 'Construct'), ('dragon', 'Dragon'), ('fiend', 'Fiend'), ('fey', 'Fey'), ('undead', 'Undead'), ('elemental', 'Elemental'), ('aberration', 'Aberration'), ('celestial', 'Celestial'), ('ooze', 'Ooze'), ('plant', 'Plant'), ('humanoid', 'Humanoid')], max_length=15, verbose_name='Tipo de Origem')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_criatura', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Componente de Criatura',
                'verbose_name_plural': 'Componentes de Criatura',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Essencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('frail', 'Frail'), ('robust', 'Robust'), ('potent', 'Potent'), ('mythic', 'Mythic'), ('deific', 'Deific')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('personagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essencias', to='campanha.personagem')),
            ],
            options={
                'verbose_name': 'Essência',
                'verbose_name_plural': 'Essências',
                'constraints': [models.UniqueConstraint(fields=('personagem', 'tier'), name='uniq_essencia_personagem')],
            },
        ),
    ]
